Первый коммит задания 4 спринта
InnaShaimina/Sprint_4 pull request #1
Opened 2023-02-05 08:41 UTC by InnaShaimina

2023-02-06 07:54 UTC, alstafeev requested changes

2023-02-06 07:54 UTC, alstafeev commented on src/test/java/yandex/scooter/pageobjects/HomePageScooterTest.java
> +        MatcherAssert.assertThat(accordeonText, is ("Сутки — 400 рублей. Оплата курьеру — наличными или картой."));
Надо поправить - надо проверять все вопросы и все ответы.

2023-02-06 07:54 UTC, alstafeev commented on src/test/java/yandex/scooter/pageobjects/HomePageScooterTest.java
> +        MatcherAssert.assertThat(accordeonText, is ("Сутки — 400 рублей. Оплата курьеру — наличными или картой."));
Надо поправить - надо проверять все вопросы и все ответы.

2023-02-06 07:54 UTC, alstafeev commented on src/test/java/yandex/scooter/pageobjects/HomePageScooterTest.java
> +    public void teardown() {
Можно лучше - вынести инициализацию вебдрайвера и закрытие браузера в базовый класс

2023-02-08 18:36 UTC, InnaShaimina commented on src/test/java/yandex/scooter/pageobjects/HomePageScooterTest.java
> +        MatcherAssert.assertThat(accordeonText, is ("Сутки — 400 рублей. Оплата курьеру — наличными или картой."));
Исправлено в последнем коммите. Все ответы в аккордеоне параметризированы

2023-02-08 18:36 UTC, InnaShaimina commented on src/test/java/yandex/scooter/pageobjects/HomePageScooterTest.java
> +        MatcherAssert.assertThat(accordeonText, is ("Сутки — 400 рублей. Оплата курьеру — наличными или картой."));
Исправлено в последнем коммите. Все ответы в аккордеоне параметризированы

2023-02-08 18:37 UTC, InnaShaimina commented on src/test/java/yandex/scooter/pageobjects/HomePageScooterTest.java
> +    public void teardown() {
Инициализация и закрытие браузера вынесены в базовый класс. Отдельные классы для chrome и firefox пока что

2023-02-10 07:14 UTC, merged